version: "3"

services:

  frontend-svc:
    build: 
      dockerfile: Dockerfile
      context: ../frontend/
    ports:
      - 8090:3000
    links:
      - backend-svc
    depends_on:
      - backend-svc
  backend-svc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    # Make sure to create your .env
    env_file: .env
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_SERVER=${MONGO_SERVER}
    links:
      - mongo_db
    depends_on:
      - mongo_db
    volumes:
      - .:/app
    restart: on-failure

  mongo_db:
    image: mongo:latest
    ports:
      - 12345:27017
    # Make sure to create your .env
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    volumes:
      - ./mongo_db:/data/db